module_name: "TCM"

buckets:
    low_frequency_tcm:
        frequency_hz: 100
        parameters:
            gearPosition_mm:
                ADC: ADC1_IN15
                sensor: linear_pos_sensor_5
                samples_buffered: 1
            clutchPosition_mm:
                ADC: ADC1_IN8
                sensor: linear_pos_sensor_50
                samples_buffered: 1
            shifterPosition_mm:
                ADC: ADC1_IN9
                sensor: linear_pos_sensor_50
                samples_buffered: 1
            tcmTargetRPM_rpm:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcmCurrentGear_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcmCurrentlyMoving_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcmAntiStallActive_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcmUsingClutch_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1
            tcmShiftState_state:
                ADC: NON_ADC
                sensor: NON_ADC
                samples_buffered: 1