module_name: "TCM"

buckets:
    low_frequency_tcm:
        frequency_hz: 100
        parameters:
            dam_chan_1:
                ADC: ADC1_IN10
                sensor: linear_pos_sensor_5
                samples_buffered: 1
            dam_chan_2:
                ADC: ADC1_IN11
                sensor: linear_pos_sensor_50
                samples_buffered: 1
            dam_chan_3:
                ADC: ADC1_IN12
                sensor: linear_pos_sensor_50
                samples_buffered: 1
            # tcm_target_rpm:
            #     ADC: NON_ADC
            #     sensor: NON_ADC
            #     samples_buffered: 1
            #     # ADC: NON_ADC
            #     # sensor: NON_ADC
            #     # samples_buffered: 1
            # tcm_trans_rpm:
            #     ADC: NON_ADC
            #     sensor: NON_ADC
            #     samples_buffered: 1
            # tcm_current_gear:
            #     ADC: NON_ADC
            #     sensor: NON_ADC
            #     samples_buffered: 1
            # tcm_currently_moving:
            #     ADC: NON_ADC
            #     sensor: NON_ADC
            #     samples_buffered: 1
            # tcm_shift_state:
            #     ADC: NON_ADC
            #     sensor: NON_ADC
            #     samples_buffered: 1
            # tcm_using_clutch:
            #     ADC: NON_ADC
            #     sensor: NON_ADC
            #     samples_buffered: 1
            # tcm_successful_shift:
            #     ADC: NON_ADC
            #     sensor: NON_ADC
            #     samples_buffered: 1
            # tcm_anti_stall:
            #     ADC: NON_ADC
            #     sensor: NON_ADC
            #     samples_buffered: 1